# Generated by Django 2.2.10 on 2020-04-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('holiday_name', models.CharField(max_length=100)),
                ('holiday_type', models.CharField(max_length=100)),
                ('comment', models.TextField(default='', max_length=100)),
            ],
        ),
    ]
