# Generated by Django 2.2.10 on 2020-04-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encashment',
            old_name='Authorize_by_Commissioner',
            new_name='Authorize_by',
        ),
    ]
