# Generated by Django 2.2.10 on 2020-05-05 02:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='medical_entitlement',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('annual_entitlement', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='medical_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_check_type', models.CharField(max_length=100)),
                ('Total_Cost', models.FloatField(default='0.0', max_length=100)),
                ('attached_receipt', models.FileField(upload_to='medical_cost/PDF')),
                ('date_you_see_the_doctor', models.DateField()),
                ('year', models.CharField(max_length=100)),
                ('I_hereby_declare_that_all_the_information_provided_above_is_true', models.BooleanField(default=True)),
                ('Status', models.CharField(choices=[('Review', 'Review'), ('Processed', 'Precessed')], default='Review', max_length=100)),
                ('process_date', models.DateField(null=True)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
